import Head from "next/head";
import InfiniteCanvas from "@/components/Canvas/Canvas";
import { useState } from "react";
import HomeScreen from "@/components/HomeScreen/HomeScreen";
import { CanvasProvider } from "@/components/Canvas/CanvasContext";
import { CursorProvider } from "@/components/Canvas/CursorContext";
import { LanguageProvider } from "@/components/Canvas/LanguageContext";

const Home = () => {
  const [showCanvas, setShowCanvas] = useState(false);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{ width: "100vw", height: "100vh" }}>
        <LanguageProvider>
          <CanvasProvider>
            {showCanvas ? (
              <CursorProvider canvasWrapperRef={{ current: document.body }}>
                <InfiniteCanvas onBack={() => setShowCanvas(false)} />
              </CursorProvider>
            ) : (
              <HomeScreen onSelectCanvas={() => setShowCanvas(true)} />
            )}
          </CanvasProvider>
        </LanguageProvider>
      </div>
    </>
  );
};

export default Home;
